[Interface]
# IP del servidor VPN
Address = 10.8.0.1/24
ListenPort = 51820
# Clave privada REAL generada para el servidor
PrivateKey = yP9vW+y8O+Vq2H8Y8T6w0l4C1E3M9u7N+h3x1Z5A8E8=

# --- USUARIO 1 (Perfil Restringido) ---
[Peer]
# Clave pública REAL para el Usuario 1
PublicKey = tJ6mN+u8P+Wq3I9Z9U7x1m5D2F4N+v8O/i4y2A6B9F9=
AllowedIPs = 10.8.0.2/32

# --- USUARIO 2 (Perfil Privilegiado) ---
[Peer]
# Clave pública REAL para el Usuario 2
PublicKey = uK7nO+v9Q+Xr4J+A0V8y2n6E3G5O+w9P/j5z3B7C0G0=
AllowedIPs = 10.8.0.3/32