# Desactivamos el servidor DNS de dnsmasq para que no se pelee con BIND9
port=0

# Escuchar en todas las interfaces para poder repartir IPs en todas las redes
bind-dynamic

# Rango dinámico para la red de Desarrollo (development_net)
dhcp-range=172.40.0.100,172.40.0.200,255.255.255.0,12h

# Rango dinámico para la red VPN (vpn_net)
dhcp-range=172.10.0.100,172.10.0.200,255.255.255.0,12h

# Asignación de rango estático (ejemplo ficticio para cumplir el punto 4 de la práctica)
dhcp-host=02:42:ac:28:00:05,172.40.0.50